name: build-and-test-differential
description: ""

inputs:
  rosdistro:
    description: ""
    required: true
  runner:
    description: ""
    required: true
  build-depends-repos:
    description: ""
    required: true
  build-pre-command:
    description: ""
    required: true
  codecov-token:
    description: ""
    required: true

runs:
  using: composite
  steps:
    - name: Show disk space before the tasks
      run: df -h
      shell: bash

    - name: Show machine specs
      run: lscpu && free -h
      shell: bash

    - name: Remove exec_depend
      uses: autowarefoundation/autoware-github-actions/remove-exec-depend@v1

    - name: Get modified packages
      id: get-modified-packages
      uses: autowarefoundation/autoware-github-actions/get-modified-packages@v1

    - name: Create ccache directory
      run: |
        mkdir -p ${CCACHE_DIR}
        du -sh ${CCACHE_DIR} && ccache -s
      shell: bash

    - name: Attempt to restore ccache
      uses: actions/cache/restore@v4
      with:
        path: |
          /root/.ccache
        key: ccache-main-${{ runner.arch }}-${{ inputs.rosdistro }}-${{ github.event.pull_request.base.sha }}
        restore-keys: |
          ccache-main-${{ runner.arch }}-${{ inputs.rosdistro }}-

    - name: Show ccache stats before build and reset stats
      run: |
        du -sh ${CCACHE_DIR} && ccache -s
        ccache --zero-stats
      shell: bash

    - name: Build
      if: ${{ steps.get-modified-packages.outputs.modified-packages != '' }}
      uses: youtalk/autoware-github-actions/colcon-build@source-opt-autoware-setup
      with:
        rosdistro: ${{ inputs.rosdistro }}
        target-packages: ${{ steps.get-modified-packages.outputs.modified-packages }}
        build-depends-repos: ${{ inputs.build-depends-repos }}
        build-pre-command: ${{ inputs.build-pre-command }}

    - name: Show ccache stats after build
      run: du -sh ${CCACHE_DIR} && ccache -s
      shell: bash

    - name: Test
      id: test
      if: ${{ steps.get-modified-packages.outputs.modified-packages != '' }}
      uses: autowarefoundation/autoware-github-actions/colcon-test@v1
      with:
        rosdistro: ${{ inputs.rosdistro }}
        target-packages: ${{ steps.get-modified-packages.outputs.modified-packages }}
        build-depends-repos: ${{ inputs.build-depends-repos }}

    - name: Upload coverage to CodeCov
      if: ${{ steps.test.outputs.coverage-report-files != '' }}
      uses: codecov/codecov-action@v4
      with:
        files: ${{ steps.test.outputs.coverage-report-files }}
        fail_ci_if_error: false
        verbose: true
        flags: differential
        token: ${{ inputs.codecov-token }}

    - name: Show disk space after the tasks
      run: df -h
      shell: bash
