name: build-and-test

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  # Ensures sequential execution of this workflow
  group: ${{ github.workflow }}
  cancel-in-progress: false

env:
  CC: /usr/lib/ccache/gcc
  CXX: /usr/lib/ccache/g++

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    container: ghcr.io/autowarefoundation/autoware:core-devel
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Show disk space before the tasks
        run: df -h

      - name: Show machine specs
        run: lscpu && free -h

      - name: Remove exec_depend
        uses: autowarefoundation/autoware-github-actions/remove-exec-depend@v1

      - name: Get self packages
        id: get-self-packages
        uses: autowarefoundation/autoware-github-actions/get-self-packages@v1

      - name: Create ccache directory
        run: |
          mkdir -p ${CCACHE_DIR}
          du -sh ${CCACHE_DIR} && ccache -s
        shell: bash

      - name: Attempt to restore ccache
        uses: actions/cache/restore@v4
        with:
          path: |
            /root/.ccache
          key: ccache-main-${{ runner.arch }}-humble-${{ github.sha }}
          restore-keys: |
            ccache-main-${{ runner.arch }}-humble-

      - name: Limit ccache size
        run: |
          rm -f "${CCACHE_DIR}/ccache.conf"
          echo -e "# Set maximum cache size\nmax_size = 600MB" >> "${CCACHE_DIR}/ccache.conf"
        shell: bash

      - name: Show ccache stats before build and reset stats
        run: |
          du -sh ${CCACHE_DIR} && ccache -s
          ccache --zero-stats
        shell: bash

      - name: Build
        if: ${{ steps.get-self-packages.outputs.self-packages != '' }}
        uses: youtalk/autoware-github-actions/colcon-build@source-opt-autoware-setup
        with:
          rosdistro: humble
          target-packages: ${{ steps.get-self-packages.outputs.self-packages }}
          build-depends-repos: build_depends.repos
          build-pre-command: taskset --cpu-list 0-6

      - name: Show ccache stats after build
        run: du -sh ${CCACHE_DIR} && ccache -s
        shell: bash

      - name: Push the ccache cache
        uses: actions/cache/save@v4
        with:
          path: |
            /root/.ccache
          key: ccache-main-${{ runner.arch }}-humble-${{ github.sha }}

      - name: Test
        if: ${{ steps.get-self-packages.outputs.self-packages != '' }}
        id: test
        uses: autowarefoundation/autoware-github-actions/colcon-test@v1
        with:
          rosdistro: humble
          target-packages: ${{ steps.get-self-packages.outputs.self-packages }}
          build-depends-repos: build_depends.repos

      - name: Upload coverage to CodeCov
        if: ${{ steps.test.outputs.coverage-report-files != '' }}
        uses: codecov/codecov-action@v5
        with:
          files: ${{ steps.test.outputs.coverage-report-files }}
          fail_ci_if_error: false
          verbose: true
          flags: total
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Show disk space after the tasks
        run: df -h
